# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0002_auto_20160503_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text1',
            field=models.CharField(default=b'\xeb\xa7\x9b', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text2',
            field=models.CharField(default=b'\xea\xb0\x80\xea\xb2\xa9', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text3',
            field=models.CharField(default=b'\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text4',
            field=models.CharField(default=b'\xeb\xb6\x84\xec\x9c\x84\xea\xb8\xb0', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text5',
            field=models.CharField(default=b'\xec\xb2\xad\xea\xb2\xb0\xeb\x8f\x84', max_length=200),
        ),
    ]
