# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0003_auto_20160503_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes5',
            field=models.IntegerField(default=0),
        ),
    ]
