# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0004_auto_20160503_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=b'\xea\xb8\xb0\xed\x83\x80\xed\x95\xad\xeb\xaa\xa9', max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
