# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0005_auto_20160503_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
