# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0007_auto_20160503_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text1',
            field=models.CharField(default=b'\xeb\xa7\x9b', max_length=201),
        ),
    ]
