# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0009_auto_20160503_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 3, 2, 5, 969466, tzinfo=utc), verbose_name=b'Published Date'),
        ),
    ]
