# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0011_auto_20160504_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2016, 5, 4), verbose_name=b'Published Date'),
        ),
    ]
