# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0012_auto_20160504_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name=b'Published Date'),
        ),
    ]
