# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0015_auto_20160504_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 5, 59, 28, 904961, tzinfo=utc), verbose_name=b'Published Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='telephone',
            field=models.CharField(default=b'\xeb\x8f\x84\xec\x8b\x9c\xeb\x9d\xbd\xec\xa7\x91 \xec\x97\xb0\xeb\x9d\xbd\xec\xb2\x98', max_length=200),
        ),
    ]
