# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 06:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0016_auto_20160504_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='question',
        ),
        migrations.RemoveField(
            model_name='clean',
            name='question',
        ),
        migrations.RemoveField(
            model_name='price',
            name='question',
        ),
        migrations.RemoveField(
            model_name='service',
            name='question',
        ),
        migrations.RemoveField(
            model_name='taste',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text1',
            field=models.CharField(default=b'\xeb\xa7\x9b', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text2',
            field=models.CharField(default=b'\xea\xb0\x80\xea\xb2\xa9', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text3',
            field=models.CharField(default=b'\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text4',
            field=models.CharField(default=b'\xeb\xb6\x84\xec\x9c\x84\xea\xb8\xb0', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text5',
            field=models.CharField(default=b'\xec\xb2\xad\xea\xb2\xb0\xeb\x8f\x84', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text6',
            field=models.CharField(default=b'100\xec\x9e\x90 \xed\x8f\x89', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='votes1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 6, 26, 32, 292541, tzinfo=utc), verbose_name=b'Published Date'),
        ),
        migrations.DeleteModel(
            name='air',
        ),
        migrations.DeleteModel(
            name='clean',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='taste',
        ),
    ]
