# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0017_auto_20160504_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='votes1',
            new_name='air',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes2',
            new_name='cleanness',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes3',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_text6',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes4',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='votes5',
            new_name='taste',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_text5',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 6, 46, 33, 561210, tzinfo=utc), verbose_name=b'Published Date'),
        ),
    ]
