# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-04 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dosirak', '0018_auto_20160504_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_air',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count_cleanness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count_service',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count_taste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 4, 7, 3, 12, 457648, tzinfo=utc), verbose_name=b'Published Date'),
        ),
    ]
